//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryServicesRefs
    {
        public int Id { get; set; }
        public int Id_entry { get; set; }
        public int Id_service { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Entries Entries { get; set; }
    }
}
