//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entries()
        {
            this.EntryServicesRefs = new HashSet<EntryServicesRefs>();
        }
    
        public int Id { get; set; }
        public int Id_customer { get; set; }
        public int Id_employee { get; set; }
        public System.DateTime start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<int> grand_total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryServicesRefs> EntryServicesRefs { get; set; }
    }
}
