//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterRatings
    {
        public int Id { get; set; }
        public int Id_master { get; set; }
        public int rating { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
