//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities1 : DbContext
    {
        public SalonEntities1()
            : base("name=SalonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EntryServicesRefs> EntryServicesRefs { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<MasterRatings> MasterRatings { get; set; }
        public virtual DbSet<Entries> Entries { get; set; }
    }
}
